// <auto-generated />
using System;
using AquariumManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquariumManager.Infrastructure.Migrations
{
    [DbContext(typeof(AquariumDbContext))]
    [Migration("20260519185759_AddAlertConfigs")]
    partial class AddAlertConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlertType")
                        .IsUnique();

                    b.ToTable("AlertConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertType = "HighMortalityRate",
                            IsEnabled = true,
                            ThresholdValue = 15m
                        });
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.FertilizationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DoseAmount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("DoseUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DosedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EstimatedIronPpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("EstimatedNitratePpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("EstimatedPhosphatePpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("EstimatedPotassiumPpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<int?>("FertilizerPresetId")
                        .HasColumnType("int");

                    b.Property<string>("FertilizerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdjustment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FertilizerPresetId");

                    b.HasIndex("TankId");

                    b.ToTable("FertilizationLogs", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.FertilizerPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultDoseAmount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("DefaultDoseUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FertilizerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("IronPerDose")
                        .HasColumnType("decimal(6,3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NitratePerDose")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhosphatePerDose")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("PotassiumPerDose")
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("FertilizerPresets", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReminderFrequencyDays")
                        .HasColumnType("int");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaterChangeLiters")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("WaterChangePercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("MaintenanceLogs", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompatibilityNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPH")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("MaxTemperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("MinPH")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("MinTemperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Species", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.SpeciesVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "VariantName")
                        .IsUnique();

                    b.ToTable("SpeciesVariants", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Co2Injection")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilterDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("HeaterSetpointCelsius")
                        .HasColumnType("decimal(4,1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LightDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("SizeLiters")
                        .HasColumnType("decimal(8,1)");

                    b.Property<string>("Substrate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TankType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Tanks", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.TankPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LinkedLogId")
                        .HasColumnType("int");

                    b.Property<string>("LinkedLogType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("TankPhotos", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.TargetParameterRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("TargetParameterRanges", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.WaterParameterLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmmoniaPpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("CarbonateHardness")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("Co2Ppm")
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GeneralHardness")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("IronPpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NitratePpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("NitritePpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PhosphatePpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("PotassiumPpm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("SalinityPpt")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int?>("TdsPpm")
                        .HasColumnType("int");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("pH")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("WaterParameterLogs", (string)null);
                });

            modelBuilder.Entity("InventoryLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeadOnArrival")
                        .HasColumnType("int");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("TotalMortality")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesVariantId");

                    b.HasIndex("SupplierId");

                    b.ToTable("InventoryLots", (string)null);
                });

            modelBuilder.Entity("MortalityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryLotId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLotId");

                    b.ToTable("MortalityRecords", (string)null);
                });

            modelBuilder.Entity("SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int?>("SpeciesVariantId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("SpeciesVariantId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.FertilizationLog", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.FertilizerPreset", "FertilizerPreset")
                        .WithMany()
                        .HasForeignKey("FertilizerPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AquariumManager.Domain.Entities.Tank", "Tank")
                        .WithMany("FertilizationLogs")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FertilizerPreset");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.FertilizerPreset", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.Species", "Species")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.Tank", "Tank")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.SpeciesVariant", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.Species", "Species")
                        .WithMany("Variants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.Tank", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.TankPhoto", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.Tank", "Tank")
                        .WithMany("TankPhotos")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.TargetParameterRange", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.Tank", "Tank")
                        .WithMany("TargetParameterRanges")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.WaterParameterLog", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.Tank", "Tank")
                        .WithMany("WaterParameterLogs")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("InventoryLot", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.SpeciesVariant", "SpeciesVariant")
                        .WithMany("InventoryLots")
                        .HasForeignKey("SpeciesVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Supplier", "Supplier")
                        .WithMany("InventoryLots")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SpeciesVariant");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MortalityRecord", b =>
                {
                    b.HasOne("InventoryLot", "InventoryLot")
                        .WithMany("MortalityRecords")
                        .HasForeignKey("InventoryLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryLot");
                });

            modelBuilder.Entity("SaleItem", b =>
                {
                    b.HasOne("AquariumManager.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquariumManager.Domain.Entities.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquariumManager.Domain.Entities.SpeciesVariant", "SpeciesVariant")
                        .WithMany()
                        .HasForeignKey("SpeciesVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Sale");

                    b.Navigation("Species");

                    b.Navigation("SpeciesVariant");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.Species", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.SpeciesVariant", b =>
                {
                    b.Navigation("InventoryLots");
                });

            modelBuilder.Entity("AquariumManager.Domain.Entities.Tank", b =>
                {
                    b.Navigation("FertilizationLogs");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("TankPhotos");

                    b.Navigation("TargetParameterRanges");

                    b.Navigation("WaterParameterLogs");
                });

            modelBuilder.Entity("InventoryLot", b =>
                {
                    b.Navigation("MortalityRecords");
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.Navigation("InventoryLots");
                });
#pragma warning restore 612, 618
        }
    }
}
